(when (equal timu-macos-flavour "dark")
  (let ((class '((class color) (min-colors 89)))
        (bg        "#222327")
        (bg-org    "#202125")
        (bg-other  "#2a2a2a")
        (macos0    "#2c2c2c")
        (macos1    "#393939")
        (macos2    "#616161")
        (macos3    "#5e5e5e")
        (macos4    "#8c8c8c")
        (macos5    "#b3b3b3")
        (macos6    "#b3b3b3")
        (macos7    "#e8e8e8")
        (macos8    "#f4f4f4")
        (fg        "#ffffff")
        (fg-other  "#dedede")

        (grey      "#8c8c8c")
        (red       "#ff6e64")
        (darkred   "#cc5850")
        (orange    "#ffb350")
        (green     "#6ae073")
        (blue      "#4e9dff")
        (magenta   "#e45c9c")
        (teal      "#91f3e7")
        (yellow    "#ffde57")
        (darkblue  "#009dff")
        (purple    "#cd7bf6")
        (cyan      "#00d1e9")
        (lightcyan "#88c0d0")
        (darkcyan  "#5297a5")

        (black     "#000000")
        (white     "#ffffff")
        ;; ms: additonal color
        (lightblue "#7abeff")

        (scale 1.0)
        )
    
    (custom-set-faces
     ;; default
     `(default ((,class (:background unspecified))))
     ;; font-lock
     `(font-lock-builtin-face ((,class (:foreground ,orange))))
     `(font-lock-type-face ((,class (:foreground ,orange))))
     `(font-lock-misc-punctuation-face ((,class (:foreground unspecified))))
     ;; highlight-symbol
     `(highlight-symbol-face
       ((,class (:background ,macos1 :weight bold))))
     ;; tab-line
     `(tab-line-tab-current ((,class (:background ,bg :foreground ,fg :weight bold))))
     `(tab-line-tab-inactive ((,class (:background ,macos0 :foreground ,fg-other))))
     `(tab-line-tab-modified ((,class (:foreground ,darkblue :slant italic))))
     ;; modeline
     `(mode-line ((,class (,@(timu-macos-mode-line-active-border blue) ,@(timu-macos-mode-line-active-background bg-org) :foreground ,fg :distant-foreground ,bg :height ,scale))))
     `(mode-line-buffer-id ((,class (:weight bold :height ,scale))))
     `(mode-line-emphasis ((,class (:foreground ,magenta :weight bold :underline ,darkcyan :height ,scale))))
     `(mode-line-highlight ((,class (:foreground ,magenta :weight bold :underline ,darkcyan :height ,scale))))
     `(mode-line-inactive ((,class (,@(timu-macos-mode-line-inactive-border macos4) ,@(timu-macos-mode-line-inactive-background bg-org) :foreground ,macos4 :distant-foreground ,macos4 :height ,scale))))
     ;; doom-modeline
     `(doom-modeline-bar ((,class (:foreground ,magenta :height ,scale))))
     `(doom-modeline-buffer-major-mode ((,class (:foreground ,magenta :height ,scale))))
     `(doom-modeline-buffer-path ((,class (:foreground ,magenta :height ,scale))))
     `(doom-modeline-eldoc-bar ((,class (:background ,green :height ,scale))))
     `(doom-modeline-evil-emacs-state ((,class (:foreground ,darkblue :weight bold :height ,scale))))
     `(doom-modeline-evil-insert-state ((,class (:foreground ,red :weight bold :height ,scale))))
     `(doom-modeline-evil-motion-state ((,class (:foreground ,purple :weight bold :height ,scale))))
     `(doom-modeline-evil-normal-state ((,class (:foreground ,green :weight bold :height ,scale))))
     `(doom-modeline-evil-operator-state ((,class (:foreground ,magenta :weight bold :height ,scale))))
     `(doom-modeline-evil-replace-state ((,class (:foreground ,teal :weight bold :height ,scale))))
     `(doom-modeline-evil-visual-state ((,class (:foreground ,yellow :weight bold :height ,scale))))
     `(doom-modeline-highlight ((,class (:foreground ,magenta :height ,scale))))
     `(doom-modeline-input-method ((,class (:foreground ,magenta :height ,scale))))
     `(doom-modeline-panel ((,class (:foreground ,magenta :height ,scale))))
     `(doom-modeline-project-dir ((,class (:foreground ,blue :weight bold :height ,scale))))
     `(doom-modeline-project-root-dir ((,class (:foreground ,magenta :height ,scale))))
     )
    )
  )
